--INSERT INTO users (yearly_salary,full_name,current_status) VALUES(200,'chaman jain','employed');
--INSERT INTO employers (company_name,address,yearly_revenue,is_hiring) VALUES('impetus','Ring Road',450,TRUE);
--INSERT INTO employers (company_name,address,yearly_revenue) VALUES('impetus','Ring Road',450);
--INSERT INTO employers (company_name,address,yearly_revenue,is_hiring) VALUES('impetus','Ring Road',450,TRUE);
