DROP TABLE USERS;
DROP TABLE addresses;
DROP TABLE cities;
CREATE TABLE USERS(
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(300) NOT NULL,
    last_name VARCHAR(300) NOT NULL,
    email VARCHAR(300) NOT NULL,
    address_id INT NOT NULL
);
CREATE TABLE ADDRESSES(
    id SERIAL PRIMARY KEY,
    street VARCHAR(300) NOT NULL,
    house_number VARCHAR(300) NOT NULL,
    city_id INT
);
CREATE TABLE cities(
    id SERIAL PRIMARY KEY,
    name VARCHAR(300) NOT NULL
);